In [1]:
import numpy as np

In [7]:
a = np.matrix([1,2,3,4,5,6]).reshape((2,3))

In [10]:
q,r = np.linalg.qr(a)

In [12]:
q

matrix([[-0.24253563, -0.9701425 ],
        [-0.9701425 ,  0.24253563]])

In [13]:
r

matrix([[-4.12310563, -5.33578375, -6.54846188],
        [ 0.        , -0.72760688, -1.45521375]])

matrix([[  1.00000000e+00,   2.22044605e-16],
        [  2.22044605e-16,   1.00000000e+00]])