In [1]:
import numpy as np

In [2]:
a = np.matrix([1,2,3,4,5,6]).reshape((2,3))

In [3]:
a

matrix([[1, 2, 3],
        [4, 5, 6]])

In [4]:
np.linalg.svd(a)

(matrix([[-0.3863177 , -0.92236578],
         [-0.92236578,  0.3863177 ]]),
 array([ 9.508032  ,  0.77286964]),
 matrix([[-0.42866713, -0.56630692, -0.7039467 ],
         [ 0.80596391,  0.11238241, -0.58119908],
         [ 0.40824829, -0.81649658,  0.40824829]]))