In [1]:
import numpy as np

In [2]:
a = np.random.randn(3, 2)
B = np.linalg.pinv(a)

In [3]:
B

array([[-0.45717882,  0.1109774 , -1.44870003],
       [ 0.42394923, -0.47839206,  0.39887097]])

In [4]:
a

array([[ 0.14150632,  0.95238143],
       [-0.52061598, -1.59906484],
       [-0.77481209, -0.42304733]])

In [6]:
np.dot(B, a)

array([[  1.00000000e+00,  -6.66133815e-16],
       [  2.22044605e-16,   1.00000000e+00]])