In [1]:
import numpy as np
from scipy import linalg as LA

In [2]:
def findspectral(a):
    zx = []
    dim = len(a)
    e_vals, z = LA.eig(a)
    zi = np.linalg.inv(z)
    anx = np.zeros((dim, dim))
    for i in range(0, dim):
        ik = np.zeros((dim, dim))
        ik[i,i] = 1
        ans = np.dot(np.dot(z, ik), zi)
        zx.append(ans)
        print('Eigen Value : ' + str(e_vals[i]))
        print(ans)
        anx += e_vals[i].real * zx[i]
    print('Answer')
    print(anx)

In [3]:
A = np.matrix([2,3,2,1])
A = A.reshape((2, 2))
findspectral(A)

Eigen Value : (4+0j)
[[ 0.6  0.6]
 [ 0.4  0.4]]
Eigen Value : (-1+0j)
[[ 0.4 -0.6]
 [-0.4  0.6]]
Answer
[[ 2.  3.]
 [ 2.  1.]]


In [4]:
A = np.matrix([0,6,0,1,0,1,1,1,0])
A = A.reshape((3, 3))
findspectral(A)

Eigen Value : (-2+0j)
[[ 0.6 -2.4  1.2]
 [-0.2  0.8 -0.4]
 [-0.2  0.8 -0.4]]
Eigen Value : (3+0j)
[[ 0.4   0.9   0.3 ]
 [ 0.2   0.45  0.15]
 [ 0.2   0.45  0.15]]
Eigen Value : (-1+0j)
[[  8.32667268e-17   1.50000000e+00  -1.50000000e+00]
 [ -1.38777878e-17  -2.50000000e-01   2.50000000e-01]
 [ -6.93889390e-17  -1.25000000e+00   1.25000000e+00]]
Answer
[[  3.60822483e-16   6.00000000e+00  -4.44089210e-16]
 [  1.00000000e+00  -2.22044605e-16   1.00000000e+00]
 [  1.00000000e+00   1.00000000e+00   0.00000000e+00]]


In [5]:
A = np.matrix([1,2,1,6,-1,0,-1,-2,-1])
A = A.reshape((3, 3))
findspectral(A)

Eigen Value : (-4+0j)
[[ 0.32142857 -0.28571429 -0.10714286]
 [-0.64285714  0.57142857  0.21428571]
 [-0.32142857  0.28571429  0.10714286]]
Eigen Value : (3+0j)
[[ 0.76190476  0.28571429  0.19047619]
 [ 1.14285714  0.42857143  0.28571429]
 [-0.76190476 -0.28571429 -0.19047619]]
Eigen Value : (9.61673583839e-17+0j)
[[-0.08333333  0.         -0.08333333]
 [-0.5         0.         -0.5       ]
 [ 1.08333333  0.          1.08333333]]
Answer
[[  1.00000000e+00   2.00000000e+00   1.00000000e+00]
 [  6.00000000e+00  -1.00000000e+00   8.40094741e-16]
 [ -1.00000000e+00  -2.00000000e+00  -1.00000000e+00]]
